# SPDX-FileCopyrightText: : 2017-2024 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0

name: pypsa-eur
channels:
- conda-forge
- bioconda
dependencies:
- python>=3.8
- pip

  # Dependencies of the workflow itself
- xlrd
- openpyxl!=3.1.1
- seaborn
- memory_profiler
- yaml
- pytables
- lxml
- numpy
- pandas>=2.1
- scipy
- pyscipopt
- matplotlib
- tqdm
- pytz
- tabula-py
- pyxlsb
- graphviz
- pre-commit

  # Keep in conda environment when calling ipython
- ipython